### ISSUE TITLE
Error while attempting to create identifier for Item id

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#35]
For non-admins, submission last step results in:

```
java.lang.RuntimeException: Error while attempting to create identifier for Item id: 6
	at cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider.mint(ConfigurableHandleIdentifierProvider.java:175)
	at cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider.register(ConfigurableHandleIdentifierProvider.java:118)
	at org.dspace.identifier.IdentifierServiceImpl.register(IdentifierServiceImpl.java:83)
	at org.dspace.content.InstallItem.installItem(InstallItem.java:78)
	at org.dspace.content.InstallItem.installItem(InstallItem.java:50)
	...
```

Related: https://github.com/marsav/lii-lindat-dspace/issues/44
More context: https://wiki.duraspace.org/display/DSPACE/AuthorisationSystem

**Comment by marsav** [comment]
dspace.log's exception:

```
2016-11-12 19:51:37,458 ERROR cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider @ martynas.savickis@bpti.lt:session_id=FD125F4FE3181D38BCD3BB0566BC0128.ajp13_worker:Error while attempting to create handle:Item id\colon; 6
java.lang.NullPointerException
    at cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider.createNewIdentifier(ConfigurableHandleIdentifierProvider.java:562)
    at cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider.mint(ConfigurableHandleIdentifierProvider.java:172)
    at cz.cuni.mff.ufal.dspace.handle.ConfigurableHandleIdentifierProvider.register(ConfigurableHandleIdentifierProvider.java:118)
    at org.dspace.identifier.IdentifierServiceImpl.register(IdentifierServiceImpl.java:83)
    at org.dspace.content.InstallItem.installItem(InstallItem.java:78)
    at org.dspace.content.InstallItem.installItem(InstallItem.java:50)
    at org.dspace.workflow.WorkflowManager.archive(WorkflowManager.java:759)
    at org.dspace.workflow.WorkflowManager.doState(WorkflowManager.java:691)
    at org.dspace.workflow.WorkflowManager.advance(WorkflowManager.java:451)
    at org.dspace.workflow.WorkflowManager.doState(WorkflowManager.java:669)
    at org.dspace.workflow.WorkflowManager.advance(WorkflowManager.java:442)
    at org.dspace.workflow.WorkflowManager.doState(WorkflowManager.java:632)
    at org.dspace.workflow.WorkflowManager.advance(WorkflowManager.java:430)
    at org.dspace.workflow.WorkflowManager.doState(WorkflowManager.java:591)
    at org.dspace.workflow.WorkflowManager.advance(WorkflowManager.java:418)
    at org.dspace.workflow.WorkflowManager.advance(WorkflowManager.java:371)
    at org.dspace.workflow.WorkflowManager.start(WorkflowManager.java:181)
    at org.dspace.submit.step.CompleteStep.doProcessing(CompleteStep.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:155)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3237)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2394)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2834)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:160)
    at org.mozilla.javascript.Context.call(Context.java:538)
    at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:1833)
    at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:1803)
    at org.apache.cocoon.components.flow.javascript.fom.FOM_JavaScriptInterpreter.handleContinuation(FOM_JavaScriptInterpreter.java:698)
    at org.apache.cocoon.components.treeprocessor.sitemap.CallFunctionNode.invoke(CallFunctionNode.java:94)
    ...
```

**Comment by marsav** [comment]
Apparently a Chrome hiccup, or some issues with db index.
After A.U. cleaned up old items, I was able to login and submit an item.
